### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by yelloxing** [etcpack/commonjs-plug#1]
为什么我使用这个插件后出现了错误：

main@v0.2.0.js:136 Uncaught TypeError: Cannot read properties of undefined (reading 'directive')     at Object.window.__etcpack__bundleSrc__.<computed> (main@v0.2.0.js:136)     at main@v0.2.0.js:1820

```js
const CommonjsPlug = require('@etcpack/commonjs-plug');

module.exports = {

    ......,
    plug: [
        ...,
        new CommonjsPlug()
    ]
};
```

运行打包后，提示打包成功：
![屏幕快照 2021-12-30 09 55 44](https://user-images.githubusercontent.com/23074691/147715865-4f38ddf5-1200-49a1-a62b-96beea6d8c8b.png)

**Comment by yelloxing** [comment]
![屏幕快照 2021-12-30 10 05 00](https://user-images.githubusercontent.com/23074691/147715895-f7b7da0c-c22a-4ece-8149-bfbae27de425.png)

**Comment by hai2007** [comment]
棒棒哒
